# Generated by Django 5.1 on 2024-10-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_email_student_mark_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('maths', models.CharField(max_length=50)),
                ('science', models.CharField(max_length=50)),
                ('social_studies', models.CharField(max_length=50)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
