# Generated by Django 5.1 on 2024-10-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
